[package]
name = "app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
shared = { workspace = true }
users = { workspace = true }
catalog = { workspace = true }
orders = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
